- services/scheduler-service/src/models/calendar.dto.ts
SFO-101
- Add the ability to add ext_id and ext_metadata along with calendar post request.
Fixes # (SFO-101)
> feat(scheduler-service): SFO-101 add ext_id along with calendar create

- services/notification-service/src/controllers/notification.controller.ts
- services/notification-service/src/enums/error-keys.enum.ts
RFIT-568
Notification user creation issue resolved .
> fix(notification-service): fix for notification user entry

- services/notification-service/src/models/notification-user.model.ts
> feat(notification-service): adds actionMeta property to NotificationUser model

- services/notification-service/src/controllers/notification-user.controller.ts
- services/notification-service/src/controllers/notification.controller.ts
> feat(notification-service): adds delete APIs for notification and notification users

- services/authentication-service/README.md
- services/authentication-service/package-lock.json
- services/authentication-service/package.json
Support for https proxy url added in auth service for keycloak auth. Just add env var named `HTTPS_PROXY` or `https_proxy`
Refer - https://github.com/sourcefuse/loopback4-authentication/commit/f89b57ebce46886d7e446fdb63a286af14faeb3e
Fixes #155 
> feat(authentication-service): upgrade loopback4-authentication package to support https proxy

- services/authentication-service/src/__tests__/acceptance/auth.acceptance.ts
- services/authentication-service/src/modules/auth/login.controller.ts
**Issue:** The Auth-token, i.e: JWT Token, is not being verified in refresh-token request. The new Auth & Refresh
Tokens can be fetched without passing the Authorization Token in request
**Solution:** Validate and map the Authorization token with the refresh-token being passed in the request before providing
the new tokens.
> feat(authentication-service): validate access token

- services/bpmn-service/src/controllers/workflow.controller.ts
- services/bpmn-service/src/providers/worker-implementation.provider.ts
- services/bpmn-service/src/types.ts
Fixed worker execution issue in bpmn service.
Type of WorkerImplementationFn
Fixes GH-233
> fix(bpmn-service): fix worker execution issue in bpmn service

- packages/core/README.md
Add `prom-client` installation steps in readme of @sourceloop/core because - 
- it is a peer-dependecy of swagger-stats since version [0.95.19](https://github.com/slanatech/swagger-stats/releases/tag/v0.95.19).
- npm 3-6 does not install peer dependencies automatically.
Fixes GH-282
> fix(core): add prom client installation step in core readme

- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
- Shepherd by default exits tour on pressing escape but this can be changed while creating tour - provided the same option to user, user can set/unset exitOnEsc property to enable/disable this behaviour.
- Added a function to hide tour - there can be a scenario where user wants to hide the tour.
> fix(user-onboarding): add option to exit tour on pressing esc, add hide tour function

- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/index.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/tour-cancel.ts
- Shepherd emits cancel event when user presses esc key in case exitOnEsc is set to true. Have emitted similar cancel event for user.
- Also have made setTourComplete function public so that user can directly access and would not have to write himself.
gh-0
> fix(user-onboarding): user gets blocked on pressing esc key - TourCancel event emitted for the same

- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/__tests__/acceptance/fixtures/product-error.repository.ts
- packages/cache/src/__tests__/acceptance/fixtures/product.repository.ts
- packages/cache/src/__tests__/unit/cache.mixin.unit.ts
- packages/cache/src/__tests__/unit/strategies/redis-cache-strategy.unit.ts
- packages/cache/src/mixins/cache.mixin.ts
- packages/cache/src/strategies/redis/redis-cache-strategy.ts
- packages/cache/src/types.ts
BREAKING CHANGES
salt is no more needed in options
Removed salt from options
Fixes #841
> fix(cache): remove salt from bcrypt

- packages/cache/README.md
- packages/cache/src/types.ts
- Restructured readme :
- changed from paragraph to bullet points
- added table for cache options
- added sheild badges for downloads, node verison, @loopback/core version
- made it more brief and precise 
- Removed Salt from cache options.
- Added scanCount to cache options
Fixes # (gh-853)
> docs(cache): restructure README.md and remove salt option

- packages/cache/src/mixins/cache.mixin.ts
- packages/cache/src/strategies/cache-strategy.ts
- packages/cache/src/strategies/redis/redis-cache-strategy.ts
- Caching was not done for findOne method. Fixed that. 
- Find One method can return null as response. Null responses are also stored in cache. Changed types for strategy interface accordingly.
Fixes # (gh-0)
> fix(cache): override findOne method and add caching to it

- .czferc.js
- lerna.json
- services/user-tenant-service/package.json
gh-1032
Removed user-tenant service from lerna ignore changes tag. So that user tenant will also get published with others.
Fixes #1032 
> fix(chore): remove user-tenant from lerna ignore

- README.md
Added missing extensions: `loopback4-kafka-client`, `loopback4-dynamic-datasource` and `loopback4-sequelize`.
> docs(readme): update related projects list

- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/src/generators/extension/index.ts
gh-1074
when a package is generated using sl extension command 
the name of the package will be one passed in options or in prompts
user can generate multiple packages no need to override the old one
Fixes #1074
> fix(cli): can generate multiple local packages using extension comamnd

- .czferc.js
- export-typedocs.ts
- File: `export-typedocs.ts`
- removed redundant console statements
- thrown errors where necessary
- File: `.czferc.js`
- added new commitzen scope called `typedoc` and `mkdocs` for related code changes in the repo
Fixes #1217
> refactor(typedoc): resolve sonar code smells

- .github/workflows/main.yml
- lerna.json
Restricting the node version in CI pipeline to 16.14.2
setting install-links to false to avoid installing the file protocol dependencies.
Fixes #1279 
> fix(chore): setting install-links to false to avoid installing the file protocol dependencies

- packages/cli/README.md
- packages/cli/src/generators/microservice/index.ts
gh-1053
When the base service does not have migrations
the user select yes for copy migrations from base service
cli throws an error and does not handle it 
now will gracefully handle the condition and not throw error .
Fixes #1053
> fix(cli): error handling if the base service does not have migrations

- packages/cli/src/generators/microservice/index.ts
sl microservice was failing to generate base migrations, when the "Include base microservice migrations" is yes, cause yoeman's fs.exists function doesn't work to check if a directory exists
GH-1358
> fix(cli): use node's fs to verify if a folder exists instead of yeoman's fs

- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/package.json
This PR adds `@oclif/plugin-help` package as cli dependency and adds up node 18 in supported engines. Earlier `@oclif/plugin-help` was in dev dependencies causing missing error when installed on a fresh machine.
While I'm not sure about the reason of keeping it in devPlugins, the motivation of moving it into main came from the popular [heroku cli configuration](https://github.com/heroku/cli/blob/4e94fb1fdc1a591bd1b744e2da69c0e0df03ed6e/packages/cli/package.json#L138).
GH-1378
Fixes #1378
> fix(cli): add help plugin as main deps

- packages/cache/README.md
- packages/cache/package-lock.json
- packages/cache/package.json
- packages/cache/src/mixins/cache.mixin.ts
- packages/cache/src/strategies/cache-strategy.ts
- packages/cache/src/types.ts
Modified types in mixin constructor to accept non defaultcrudrepositories as well
GH-1427
Fixes #1427
> feat(cache): add sequelize support in mixin

- services/authentication-service/src/models/refresh-token.model.ts
- services/authentication-service/src/modules/auth/login.controller.ts
- services/authentication-service/src/modules/auth/models/auth-refresh-token-request.dto.ts
- services/authentication-service/src/providers/jwt-payload.provider.ts
- services/authentication-service/src/providers/types.ts
fixed refresh token API creating access token with default tenant id.
GH-1430
- Added auth token switch API that will switch access token's tenant id with the required tenant id.
Fixes #1430 
> fix(authentication-service): fix refresh token api creating access token with default tenant id.

- packages/cache/package-lock.json
- packages/cache/package.json
Removes node v14 support, It was missed in #1411.
End of life of node v14
GH-1382
> chore(cache): remove node v14 support

- package-lock.json
- package.json
#1437 updated it to the breaking one. See: https://github.com/TypeStrong/typedoc/releases/tag/v0.24.0
Fixes #1459 
> fix(typedoc): use typedoc@0.23.23 statically

- packages/cli/package-lock.json
- packages/ocr-parser/package-lock.json
- packages/search/package-lock.json
- packages/user-onboarding/package-lock.json
- sandbox/auth-multitenant-example/package-lock.json
- sandbox/chat-notification-socketio-example/services/socketio-service/package-lock.json
- sandbox/oauth-example/auth-service/package-lock.json
- sandbox/oauth-example/frontend/package-lock.json
- sandbox/search-client-example/package-lock.json
- sandbox/user-tenant-example/package-lock.json
- sandbox/workflow-ms-example/package-lock.json
- services/scheduler-service/package-lock.json
- services/video-conferencing-service/package-lock.json
✅ This PR was created by the Combine PRs action by combining the following PRs:
#1472 chore(deps): bump ua-parser-js from 0.7.31 to 0.7.35 in /packages/ocr-parser
#1470 chore(deps): bump ua-parser-js from 0.7.31 to 0.7.35 in /packages/user-onboarding
#1468 chore(deps): bump ua-parser-js from 0.7.32 to 0.7.35 in /sandbox/search-client-example
#1467 chore(deps): bump dns-packet from 5.3.1 to 5.6.0 in /packages/user-onboarding
#1466 chore(deps): bump socket.io-parser from 4.2.2 to 4.2.4 in /packages/search
#1465 chore(deps): bump engine.io from 6.4.0 to 6.4.2 in /packages/search
#1464 chore(deps): bump dottie from 2.0.3 to 2.0.6 in /services/video-conferencing-service
#1463 chore(deps): bump dottie from 2.0.3 to 2.0.6 in /services/scheduler-service
#1276 build(deps): bump …
> chore(deps): combine dependabot updates

- packages/feature-toggle/README.md
- packages/feature-toggle/src/component.ts
- packages/feature-toggle/src/decorators/feature-flag.decorator.ts
- packages/feature-toggle/src/index.ts
- packages/feature-toggle/src/providers/feature-flag-action.provider.ts
- packages/feature-toggle/src/services/feature-handler-service.ts
- packages/feature-toggle/src/services/index.ts
- packages/feature-toggle/src/types.ts
- services/feature-toggle-service/migrations/20230612141912-update-tables.js
- services/feature-toggle-service/migrations/sqls/20230612141912-update-tables-down.sql
- services/feature-toggle-service/migrations/sqls/20230612141912-update-tables-up.sql
MIGRATION CHANGE:
migration-20230612141912- add metadata column
gh-1447
Supersedes: #1448
Once you check if a feature is allowed to a particular user or not and incase it is allowed one wants to do specific handling on the that particular feature or handle any use case then provide a handler name in the decorator. 
That handler should implement  FeatureHandler interface that has the same name as that mentioned in the decorator.
This handler will be called via an extension point FeatureHandlerService.
This service will return true or false and further decide if a feature is allowed or not.
Fixes #1447
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for …
> feat(feature-toggle): add handler service to handle anything specific after feature check

- .github/workflows/combine-prs.yml
This PR Adds `Closes` keyword before the successfully merged PR numbers so that GitHub automatically closes the individual PRs when the combined PR is merged.
> feat(workflows): close individual PRs when combined PR is merged

- packages/core/src/secure-sequence.ts
This PR moves `findRoute` call to the top in `SecureSequence` so that ratelimit action below it can get the values of `CoreBindings.CONTROLLER_CLASS` and method name bindings.
Read #1600
Fixes #1600 
> fix(core): move `findRoute` to the top in SecureSequence

- .github/workflows/main.yml
- .github/workflows/release.yml
This PR updates the node version in our Release and CI GitHub Action along with other refactoring.
> fix(workflows): use lts of node in release and ci actions

- packages/core/src/component.ts
- packages/core/src/types.ts
This PR introduced a callback in core config named `modifyPathDefinition` in order to allow users to modify or even exclude the path from swagger spec received by swagger-stats middleware.
GH-1613
Fixes #1613 
> feat(core): add ability alter the paths definition received by swagger stats

- packages/core/package-lock.json
- packages/core/package.json
This PR removes explicit dependency of casbin in `@sourceloop/core` as it is not used directly. (Read #1658)
Fixes #1658
> refactor(deps): remove explicit dependency of casbin in core

- packages/search/projects/search-lib/src/lib/search/search.component.ts
add null check for model name in custom search event before setting the category 
Fixes # ([GH-1764](https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1674))
> fix(search): add null check for model name in custom search event before set the category

- packages/cli/src/generators/microservice/index.ts
lambda files should only be generated if opted for cdk
gh-1698
Fixes #1698 
> fix(cli):  lambda files should only be generated if opted for cdk

- services/authentication-service/src/repositories/role.repository.ts
- services/authentication-service/src/repositories/tenant.repository.ts
- services/authentication-service/src/repositories/user-tenant.repository.ts
- services/authentication-service/src/repositories/user.repository.ts
gh-1223
repositories now allow user to override model reference
RoleRepository
TenantRepository
UserTenantRepository
UserRepository
Fixes #1223 
Within my testApp created a new model for User that extends the existing model 
added an extra property to it ..
The @get call returns the new property as well
> feat(authentication-service): repositories now allow user to override model reference

- services/survey-service/migrations/sqls/20230619123543-create-questions-down.sql
- services/survey-service/migrations/sqls/20230619123543-create-questions-up.sql
- services/survey-service/migrations/sqls/20230619123601-create-question-options-down.sql
- services/survey-service/migrations/sqls/20230619123601-create-question-options-up.sql
- services/survey-service/migrations/sqls/20230621082309-create-question-templates-down.sql
- services/survey-service/migrations/sqls/20230621082309-create-question-templates-up.sql
- services/survey-service/migrations/sqls/20230621113225-create-template-questions-down.sql
- services/survey-service/migrations/sqls/20230621113225-create-template-questions-up.sql
- services/survey-service/migrations/sqls/20230621164240-create-survey-down.sql
- services/survey-service/migrations/sqls/20230621164240-create-survey-up.sql
- services/survey-service/migrations/sqls/20230621164337-create-survey-questions-down.sql
- services/survey-service/migrations/sqls/20230621164337-create-survey-questions-up.sql
- services/survey-service/migrations/sqls/20230622111309-sections-down.sql
- services/survey-service/migrations/sqls/20230622111309-sections-up.sql
- services/survey-service/migrations/sqls/20230622111907-survey-responders-down.sql
- services/survey-service/migrations/sqls/20230622111907-survey-responders-up.sql
- services/survey-service/migrations/sqls/20230622112026-survey-cycles-down.sql
- services/survey-service/migrations/sqls/20230622112026-survey-cycles-up.sql
- services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-down.sql
- services/survey-service/migrations/sqls/20230622112223-survey-cycle-responses-up.sql
- services/survey-service/migrations/sqls/20230622112646-survey-response-details-down.sql
- services/survey-service/migrations/sqls/20230622112646-survey-response-details-up.sql
MIGRATION CHANGE:
migration-20230619123543- convert survey service migrations in postgresql migration-20230619123601- convert survey service migrations in postgresql migration-20230621082309- convert survey service migrations in postgresql migration-20230621113225- convert survey service migrations in postgresql migration-20230621164240- convert survey service migrations in postgresql migration-20230621164337- convert survey service migrations in postgresql migration-20230622111309- convert survey service migrations in postgresql migration-20230622111907- convert survey service migrations in postgresql migration-20230622112026- convert survey service migrations in postgresql migration-20230622112223- convert survey service migrations in postgresql migration-20230622112646- convert survey …
> fix(survey-service): convert survey service migrations in postgresql

- packages/cli/src/generators/microservice/templates/Dockerfile
gh-1830
the npm ci command in dockerfile throws error as it requires package-lock.json file
changed the npm ci to npm i 
Fixes #1830
> fix(cli): change the npm ci to npm i in docker file of microservice

- services/user-tenant-service/src/index.ts
add missing exports in user tenant service
1901
Fixes #1901 
> fix(user-tenant-service): add missing exports in user tenant service

- package-lock.json
- services/audit-service/package.json
- services/audit-service/src/services/audit-log-export.service.ts
audit service will now use exceljs instead of xlsx
Fixes #1970 
> fix(audit-service): remove xlsx dependecy from audit service

- services/task-service/src/__tests__/acceptance/task.controller.acceptance.ts
- services/task-service/src/__tests__/fixtures/mock-data.ts
- services/task-service/src/controllers/task.controller.ts
- services/task-service/src/models/task.model.ts
- services/task-service/src/services/camunda.service.ts
1. Delete process instances on Camunda for deleted tasks.
2. Remove ? to mark externalId as mandatory field.
3. Add Camunda's process instances delete API to delete for process instances from Camunda 
Fixes GH-1972
> feat(task-service): delete process instances on Camunda for deleted tasks

- .czferc.js
- .github/workflows/release.yml
gh-00
This change is to temporarily fix the release failure as linux specific nx dependency is not being installed during the ci step 
Should be removed later
> chore(ci-cd): update the release workflow to explicitly install linux deps

- package-lock.json
- services/search-service/README.md
- services/search-service/migrations/mysql/migrations/20240405080334-recent-search.js
- services/search-service/migrations/mysql/migrations/sqls/20231221041306-init-up.sql
- services/search-service/migrations/mysql/migrations/sqls/20240405080334-recent-search-down.sql
- services/search-service/migrations/mysql/migrations/sqls/20240405080334-recent-search-up.sql
- services/search-service/migrations/pg/migrations/20240403122951-recent-search.js
- services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-down.sql
- services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-up.sql
- services/search-service/package.json
- services/search-service/src/component.ts
- services/search-service/src/keys.ts
- services/search-service/src/models/search-query.model.ts
- services/search-service/src/repositories/search-query.repository.ts
- services/search-service/src/repositories/sequelize/index.ts
- services/search-service/src/repositories/sequelize/recent-search.repository.ts
- services/search-service/src/repositories/sequelize/search-query.repository.ts
- services/search-service/src/services/model.provider.ts
- services/search-service/src/services/sequelize/index.ts
- services/search-service/src/services/sequelize/search.provider.ts
- services/search-service/src/types.ts
add sequelize support in search service
GH-1350
add sequelize support in search service
Fixes #1350
> feat(search-service): add sequelize support in search service

- services/audit-service/README.md
- services/audit-service/package.json
Auditexportlogprovider and its exceljs deps is made optional by providing separate export path in packagejson file.
(major change)
Auditexportlogprovider and its exceljs deps is made optional by providing separate export path in packagejson file.
GH-2088
Auditexportlogprovider and its exceljs deps is made optional by providing separate export path in packagejson file.
Fixes #2088 
> feat(audit-service): bump major version

- packages/cli/src/generators/cdk/index.ts
- packages/core/src/types.ts
- services/task-service/src/commands/create-task.ts
- services/task-service/src/services/event-processor.service.ts
fix sonar issues
2126
Fixes #2126 
> fix(deps): fix sonar issues

- packages/core/src/repositories/default-transactional-user-modify-repository.base.ts
- packages/core/src/repositories/default-user-modify-crud.repository.base.ts
gh-2158
createdon modifiedon can not be changed via input
even if its passed in the input we will delete the fields and update it from db
Fixes #2158 
> fix(core): createdon modifiedon can not be changed via input

- sandbox/chat-notification-socketio-example/services/socketio-service/src/controllers/socketio.controller.ts
- sandbox/oauth-example/src/controllers/ping.controller.ts
- sandbox/workflow-ms-example/src/application.ts
- services/reporting-service/src/controllers/state-tracking.controller.ts
- services/search-service/src/decorators/authentication-conditional.decorator.ts
- services/search-service/src/decorators/get-conditional.decorator.ts
- services/task-service/src/repositories/sequelize/event-workflow.repository.ts
- services/task-service/src/repositories/sequelize/task-workflow.repository.ts
- services/task-service/src/repositories/sequelize/task.repository.ts
- services/task-service/src/repositories/sequelize/user-task.repository.ts
resolve sonar issues
GH-2177
resolve sonar issues
Fixes #2177 
> chore(ci-cd): resolve sonar issues

- packages/core/src/components/logger-extension/winston/logger-console.ts
- services/authentication-service/src/__tests__/unit/bearer-verify.provider.unit.ts
- services/notification-service/src/__tests__/unit/process-notification.service.unit.ts
refactor test case of auth service core and notif service
Fixes #2229
> fix(all-services): refactor test case of auth service core and notification service

- sandbox/auth-ms-basic-example/migrations/sqls/20210421113146-seed-up.sql
update the sandbox sql seed file based on latest db schema
MIGRATION CHANGE:
migration-20210421113146- seed update
gh-00
update the sandbox sql seed file based on latest db schema
Executed the script and tested it.
> refactor(sandbox): update the sandbox sql seed file based on latest db schema

- services/bpmn-service/src/__tests__/unit/register-worker.unit.ts
- services/bpmn-service/src/__tests__/unit/worker-implementation.provider.unit.ts
- services/bpmn-service/src/providers/register-worker.service.ts
- services/bpmn-service/src/providers/worker-implementation.provider.ts
- services/bpmn-service/src/types/types.ts
- services/task-service/src/lifecycle-observers/command.observer.ts
add new worker key inProgress to handle OptimisticLockingException error.
when the worker id is generated for a topic in bpmn serivice, the same id is being picked after some time and the command tries to make it complete again. that is causing OptimisticLockingException error.
on introducing new key inProgress in the worker, it will ensure that the job will be picked only once if inProgress is true.
- Ran test cases and updated the failing test cases beacuse of the new changes.
- Ran bpmn package build locally in my service to verify the changes.
> fix(bpmn-service): add new worker key to handle OptimisticLockingException error

- packages/file-utils/src/__tests__/integration/file-uploader.integration.ts
- packages/file-utils/src/__tests__/integration/fixtures/controllers/multipart.controller.ts
- packages/file-utils/src/__tests__/integration/fixtures/models/index.ts
- packages/file-utils/src/__tests__/integration/fixtures/models/multipart.model.ts
- packages/file-utils/src/__tests__/integration/fixtures/test.application.ts
- packages/file-utils/src/constant.ts
- packages/file-utils/src/decorators/file-property.decorator.ts
- packages/file-utils/src/decorators/multipart-request-body.decorator.ts
- packages/file-utils/src/services/file-validator.provider.ts
- packages/file-utils/src/services/multer-storage.provider.ts
- packages/file-utils/src/services/validators/file-name-validator.provider.ts
- packages/file-utils/src/services/validators/file-type-validator.provider.ts
- packages/file-utils/src/services/validators/index.ts
- packages/file-utils/src/sub-packages/clamav/validators/clamav-validator.provider.ts
- packages/file-utils/src/types.ts
- remove direct export of clamav to avoid direct dependency on clamav to avoid making it a required dependency
- it can now be used only through the sub-package
- better handling of the multipart request schema for openapi-spec
- improved stream handling slightly, but there is still scope for improvement 
- remove file on error in any of the validators
> fix(file-utils): remove direct export of clamav to avoid direct dep

- packages/cache/src/__tests__/acceptance/cache-repository.mixin.acceptance.ts
- packages/cache/src/__tests__/fixtures/models/index.ts
- packages/cache/src/__tests__/fixtures/models/test-2.model.ts
- packages/cache/src/__tests__/fixtures/repositories/test-2-with-mixin.repository.ts
- packages/cache/src/__tests__/helpers/test-builder.ts
- packages/cache/src/__tests__/integration/cache-repository.mixin.integration.ts
- packages/cache/src/services/cache.service.ts
- removed the `uninvalidate` call as it can undo invalidation on any subsequent get, even with a different filter.
- added test case to cover this exact scenario
- refactored the tests a bit for better timeout handling
Fixes GH-2249
> fix(cache): remove uninvalidate as it can undo invalidation in case of subsequent get

- services/authentication-service/src/services/idp-login.service.ts
update last login after user authentication in login API
PLM-2311
update last login after user authentication in login API
Fixes #2311 
> fix(authentication-service): update last login after user authentication in login API
