- LICENSE
Added license document
Fixes # SFO-20
> docs(core): add license doc

- services/video-conferencing-service/README.md
add docs related to video conferencing service, features, configuration and APIs
SFO-77
> docs(video-conferencing-service): add documentation in README.md

- services/scheduler-service/migrations/20200616144253-update-schduler-identifier.js
- services/scheduler-service/migrations/sqls/20200616144253-update-schduler-identifier-down.sql
- services/scheduler-service/migrations/sqls/20200616144253-update-schduler-identifier-up.sql
- services/scheduler-service/src/models/attendee.model.ts
- services/scheduler-service/src/models/calendar.model.ts
- services/scheduler-service/src/models/event.dto.ts
- services/scheduler-service/src/models/event.model.ts
- services/scheduler-service/src/models/subscription.model.ts
- services/scheduler-service/src/types.ts
fix(scheduler-service): SFO-86 make scheduler identifier generic
SFO-86
> fix(scheduler-service): SFO-86 make scheduler identifier generic

- services/video-conferencing-service/.prettierignore
- services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts
- services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts
- services/video-conferencing-service/src/__tests__/unit/providers/vonage.provider.unit.ts
- services/video-conferencing-service/src/component.ts
- services/video-conferencing-service/src/controllers/video-chat-archive.controller.ts
- services/video-conferencing-service/src/controllers/video-chat-session.controller.ts
- services/video-conferencing-service/src/providers/vonage/vonage.provider.ts
- services/video-conferencing-service/src/providers/vonage/vonage.service.ts
- services/video-conferencing-service/src/repositories/audit-logs.repository.ts
- services/video-conferencing-service/src/repositories/session-attendees.repository.ts
SFO-81
refactor(video-conferencing-service): fix lint issues and run prettier
> refactor(video-conferencing-service): fix lint issues and run prettier

- services/scheduler-service/package-lock.json
- services/scheduler-service/package.json
- services/scheduler-service/src/__tests__/unit/calendar-event.service.unit.ts
> fix(scheduler-service): SFO-92 lint fix

- services/scheduler-service/package.json
SFO-92
fix(scheduler-service): SFO-92 add jsonwebtoken as dev dependency
> fix(scheduler-service): SFO-92 add jsonwebtoken as dev dependency

- services/scheduler-service/migrations/20200625061758-create-audit-trigger.js
- services/scheduler-service/migrations/sqls/20200625061758-create-audit-trigger-down.sql
- services/scheduler-service/migrations/sqls/20200625061758-create-audit-trigger-up.sql
SFO-21
fix(scheduler-service): SFO-21 add audit triggers to database tables
> fix(scheduler-service): SFO-21 add audit triggers to database tables

- packages/core/src/secure-sequence.ts
- packages/core/src/service-sequence.ts
Fixes cors issue as per https://github.com/strongloop/loopback-next/issues/5368#issuecomment-626233755
> fix(core): cors issue fix

- services/scheduler-service/src/controllers/event.controller.ts
> feat(scheduler-service): add delete event with attachments and attendees

- services/video-conferencing-service/src/enums/permission-keys.enum.ts
> refactor(video-conferencing-service): modifiy naming convention of permission enums

- services/scheduler-service/src/controllers/calendar.controller.ts
- services/scheduler-service/src/models/enums/error-keys.ts
SFO-102
- Added required permissions in calendar
Fixes # (SFO-102)
> feat(scheduler-service): SFO-102 add permissions in calendar

- packages/core/src/models/user-modifiable-entity.model.ts
changed datatype of createdBy and modifiedBy to string inside property decorator
SFO-104
> fix(core): fix datatype issue of createdBy and modifiedBy SFO-104

- services/scheduler-service/src/controllers/calendar.controller.ts
- services/scheduler-service/src/services/event.service.ts
SFO-105
- Add cancelled event consition in event free busy api.
Fixes # (SFO-105)
> feat(scheduler-service): add cancelled event consition in free busy api

- services/scheduler-service/migrations/20200707111059-add-modifiedOn-triggers.js
- services/scheduler-service/migrations/scheduler.dbs
- services/scheduler-service/migrations/sqls/20200707111059-add-modifiedOn-triggers-down.sql
- services/scheduler-service/migrations/sqls/20200707111059-add-modifiedOn-triggers-up.sql
on updation of table values the modifiedOn will be updated to the date time of the update
SFO-106
> feat(scheduler-service): SFO-106 add update triggers

- services/scheduler-service/src/__tests__/acceptance/subscription.controller.acceptance.ts
- services/scheduler-service/src/controllers/subscription.controller.ts
> feat(scheduler-service): SFO-109 add subcription get API 

- services/video-conferencing-service/package-lock.json
- services/video-conferencing-service/package.json
- services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts
- services/video-conferencing-service/src/controllers/video-chat-session.controller.ts
- services/video-conferencing-service/src/enums/permission-keys.enum.ts
> feat(video-conferencing-service): add PATCH /session/{meetingLink} API to edit meeting details and add unit tests

- services/authentication-service/package-lock.json
- services/authentication-service/package.json
- services/authentication-service/src/component.ts
- services/authentication-service/src/index.ts
- services/authentication-service/src/modules/auth/providers/google-oauth2-verify.provider.ts
- services/authentication-service/src/providers/google-oauth2-signup.provider.ts
- services/authentication-service/src/providers/index.ts
- services/authentication-service/src/providers/keys.ts
- services/authentication-service/src/providers/types.ts
Google Sign up provider is being used to sign up user to our system while trying to login with google
> feat(authentication-service): google signup provider for creating user while logging with google

- services/authentication-service/src/__tests__/acceptance/auth.acceptance.ts
- services/authentication-service/src/models/user.model.ts
- services/authentication-service/src/modules/auth/login.controller.ts
- services/authentication-service/src/modules/auth/providers/resource-owner-verify.provider.ts
authClientIds now a string type in user model
User login flow is impacted if auth client id was  getting used.
> fix(authentication-service): change in user model

- services/authentication-service/src/modules/auth/login.controller.ts
- services/authentication-service/src/modules/auth/providers/resource-owner-verify.provider.ts
when authClientIds return from db it is an array
this will break login flow
SFO-0
> fix(authentication-service): change in condition of auth clientID

- services/authentication-service/src/modules/auth/login.controller.ts
returning the username in google auth redirect as there no way to getting username in /auth/token
API
SFO-0
> fix(authentication-service): change in login.controller.ts

- packages/core/CHANGELOG.md
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/component.ts
- packages/core/src/keys.ts
- packages/core/src/types.ts
- services/video-conferencing-service/CHANGELOG.md
SFO-126
make initialisation object of i18n configurable
#56 
> feat(core): make initialisation object of i18n configurable

- services/in-mail-service/migrations/migrations/20200805162829-inmail-init.js
> fix(in-mail-service): fix identation using prettier

- services/scheduler-service/src/models/attachment.model.ts
- services/scheduler-service/src/models/attendee.model.ts
- services/scheduler-service/src/models/audit-log.model.ts
- services/scheduler-service/src/models/calendar.dto.ts
- services/scheduler-service/src/models/calendar.model.ts
- services/scheduler-service/src/models/event-attendee-view-item.dto.ts
- services/scheduler-service/src/models/event.dto.ts
- services/scheduler-service/src/models/event.model.ts
- services/scheduler-service/src/models/settings.model.ts
- services/scheduler-service/src/models/subscription.model.ts
- services/scheduler-service/src/models/theme.model.ts
- services/scheduler-service/src/models/working-hour.model.ts
> SFO-159: feat: change the type of ext_metadata from object to AnyObject in scheduler service

- packages/core/src/component.ts
Signed-off-by: mayank <mayank.nauriyal@sourcefuse.com>
Translation config was improperly handled in core component.
> fix(core): fix for translations config binding bug

- services/notification-service/src/controllers/notification.controller.ts
Added logic to create a notification user entry along with notification creation.
> fix(notification-service): notification user creation along with notification

- services/notification-service/src/controllers/notification.controller.ts
bulk notification fix for accepting array and showing the same in swagger
Signed-off-by: mayank <mayank.nauriyal@sourcefuse.com>
> fix(notification-service): fix for sending bulk notifications

- services/notification-service/src/component.ts
- services/notification-service/src/controllers/notification-user.controller.ts
- services/notification-service/src/models/notification-user.model.ts
RFIT-568
notification is read set to false as default.
> fix(notification-service): notification is read set to false as default

- services/authentication-service/src/models/user.model.ts
> feat(authentication-service): adds fullName property to user model

- packages/core/src/repositories/default-transactional-user-modify-repository.base.ts
- packages/core/src/repositories/index.ts
Added Transaction Base Repository
> feat(Transactional Repo): Added base repo

- services/notification-service/src/component.ts
- services/notification-service/src/controllers/notification.controller.ts
- services/notification-service/src/keys.ts
- services/notification-service/src/providers/notification-user.service.ts
- services/notification-service/src/types.ts
update method to fetch user id for notification user.
> fix(notification-service): update method to fetch user id for notification user

- package-lock.json
- package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/component.ts
- packages/core/src/types.ts
- services/authentication-service/package-lock.json
added swagger-stats in core so every project built using sourceloop has functionality to create
system & app metrics
> feat(core): SFO-169: added metrics functionality in core

- packages/core/src/component.ts
> fix(core): change in core to rectify publish issue

- services/notification-service/src/controllers/notification-user.controller.ts
> fix(notification-service): hard deleting notif users for gdpr compliance

- packages/core/src/casbin-secure-sequence.ts
- packages/core/src/component.ts
- packages/core/src/keys.ts
- packages/core/src/secure-sequence.ts
- packages/core/src/service-sequence.ts
- packages/core/src/types.ts
- sandbox/auth-multitenant-example/package.json
- sandbox/auth-multitenant-example/public/index.html
- sandbox/auth-multitenant-example/src/application.ts
- sandbox/auth-multitenant-example/src/openapi-spec.ts
- sandbox/auth-multitenant-example/src/openapi.json
1. Added swagger stats in sourceloop/core sequences
2. Added sandbox test for swagger stats
RPMS-2770, RPMS-2771
> feat(core): added swagger stats

- packages/core/src/casbin-secure-sequence.ts
- packages/core/src/component.ts
- packages/core/src/secure-sequence.ts
- packages/core/src/service-sequence.ts
- sandbox/auth-multitenant-example/package-lock.json
- sandbox/auth-multitenant-example/package.json
- sandbox/auth-multitenant-example/src/application.ts
1. Added response object in auth request call to fix redirect issues
2. Added check to see if express middlewares have generated response
3. Added express middleware `morgan` in sandbox for testing
> fix(core): fixes in auth action in sequence

- services/audit-service/package-lock.json
- services/audit-service/package.json
RPMS-4260
updated audit log version which solves a bug where duplicated log was getting created for updateById
and added optional noAudit flag to functions
> feat(audit-service): updated audit log version to 1.2.0

- services/audit-service/README.md
- services/audit-service/package-lock.json
- services/audit-service/package.json
fixed prom client issue, minor change in readme
> fix(audit-service): fixed prom client issue, minor change in readme

- packages/core/src/component.ts
- packages/core/src/types.ts
Swagger stats authentication to stop authorisation bypass via forceful browsing.
> fix(core): Swagger stats authentication

- services/audit-service/migration.js
- services/authentication-service/migration.js
- services/bpmn-service/migration.js
- services/in-mail-service/migration.js
- services/notification-service/migration.js
- services/scheduler-service/migration.js
- services/video-conferencing-service/migration.js
- services/video-conferencing-service/src/index.ts
fixed missing exports in Video Conferencing service, removed migration dependency in case migrations are disabled for any service.
Fixes #219
> fix(video-conferencing-service): fixed missing exports

- sandbox/audit-ms-example/Dockerfile
- sandbox/auth-ms-basic-example/Dockerfile
- sandbox/auth-multitenant-example/Dockerfile
- sandbox/in-mail-example/Dockerfile
- sandbox/notification-socket-example/Dockerfile
- sandbox/scheduler-example/Dockerfile
- sandbox/video-conferencing-ms-example/Dockerfile
- sandbox/workflow-ms-example/Dockerfile
Updated Dockerfiles as nodejs version 10 has reached its EOL, nodejs 14 is actively maintained
Ref: https://nodejs.org/en/about/releases/
> fix(core): update nodejs version in docker file to latest

- DEVELOPING.md
- services/video-conferencing-service/src/index.ts
added more exports, fixed development.md
> fix(video-conferencing-service): added more exports, fixed development.md

- packages/core/src/utils.ts
Add rate limit key prefix for case of microservices
Fixes #249 
> fix(core): fix rate limit key prefix issue

- sandbox/workflow-ms-example/src/providers/bpmn.provider.ts
- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/authentication-service/src/controllers/index.ts
- services/bpmn-service/README.md
> fix(bpmn-service): fix readme for bpmn service

- packages/core/src/enums/status-codes.enum.ts
Fixed linting issue in @sourceloop/core added in one of the PRs.
> fix(core): fix linting issue in core

- .gitignore
> chore(core): add DS_Store to gitignore

- lerna.json
- packages/search/projects/search-lib/src/lib/search/search.component.html
- packages/search/projects/search-lib/src/lib/search/search.component.ts
- services/search-service/src/controllers/search.controller.ts
reduce gap between input box and recent searches if no result found & do not open drop down in case no recent searches
Reduce gap between input box and recent searches if no result found & do not open drop down in case no recent searches
> fix(search-client): reduce gap between input box and recent searches 

- packages/search/projects/search-lib/package.json
> perf(search-client): updating package for release

- packages/search/projects/search-lib/package.json
- packages/search/projects/search-lib/src/lib/lib-configuration.ts
- packages/search/projects/search-lib/src/lib/search/search.component.html
- packages/search/projects/search-lib/src/lib/search/search.component.scss
- packages/search/projects/search-lib/src/lib/search/search.component.ts
Add placeholder function, reduce width.
> feat(search-client): add placeholder function, reduce width

- .czferc.js
- lerna.json
- packages/search/projects/search-lib/package-lock.json
- packages/search/projects/search-lib/package.json
- packages/user-onboarding/.gitignore
- packages/user-onboarding/README.md
- packages/user-onboarding/package-lock.json
- packages/user-onboarding/package.json
- packages/user-onboarding/projects/user-onboarding-lib/README.md
- packages/user-onboarding/projects/user-onboarding-lib/ng-package.json
- packages/user-onboarding/projects/user-onboarding-lib/package-lock.json
- packages/user-onboarding/projects/user-onboarding-lib/package.json
changed lerna.json to always update inner package.json and package-lock.json in case of user-onboarding. also now dist folder is created inside and not in root directory.
gh-0
> fix(user-onboarding): fix publishing issue - package.json not updated on publish using lerna

- .czferc.js
- packages/custom-sf-changelog/package-lock.json
update package-lock.json with public npm registry reference instead of local one. Also added custom-sf-changelog to scopes.
gh-0
> fix(custom-sf-changelog): fix npm_audit failing on lerna bootstrap

- services/feature-toggle-service/src/component.ts
- services/feature-toggle-service/src/providers/feature-flag-action.provider.ts
> fix(feature-toggle-service): minor fixes

- lerna.json
- packages/custom-sf-changelog/package-lock.json
Added sandbox examples to ignore of bootstrap
> fix(ci-cd): add sandbox to ignore for bootstrap

- packages/search/projects/search-lib/package.json
- packages/user-onboarding/projects/user-onboarding-lib/package.json
> fix(ci-cd): version increase to to skip tags error GH-00

- DEVELOPING.md
- package.json
GH-0
added script to init husky, to initialize husky - 
- run `npm i` at the root of the project
- run `npm run prepare`
-
> fix(core): add script to init husky

- services/notification-service/package.json
add packages required by notification service
> fix(notification-service): add packages required by notification service

- services/authentication-service/src/services/login-helper.service.ts
not able to find clientId in authClientIds
> fix(authentication-service): authclientId issue

- packages/cli/generators/extension/index.js
- packages/cli/generators/microservice/index.js
- packages/cli/generators/spawn.js
Created sourceloop-cli with scaffold, microservice and extension generators.
> feat(cli): sourceloop-cli update

- services/feature-toggle-service/src/controllers/features.controller.ts
- services/feature-toggle-service/src/controllers/projects.controller.ts
- services/feature-toggle-service/src/controllers/strategies.controller.ts
- services/feature-toggle-service/src/enums/index.ts
- services/feature-toggle-service/src/enums/pemission-key.enum.ts
added permissions and a delete endpoint for features.
> feat(feature-toggle-service): added permissions and a delete method

- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/constants.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/tour-button.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/tour-step.ts
- user can set max wait time for tour to start initially
- in case tour doesn't start, there was no way for user to know, added observable for the same (putting everything inside try catch block from user side and throwing error from library didn't work because of asynchronous calls made from library)
> fix(user-onboarding): add max wait time, add observable for error handling

- services/feature-toggle-service/package-lock.json
- services/feature-toggle-service/package.json
- services/feature-toggle-service/src/__tests__/fixtures/application.ts
- services/feature-toggle-service/src/__tests__/fixtures/system-feature-test.provider.ts
- services/feature-toggle-service/src/__tests__/fixtures/test-helper.ts
- services/feature-toggle-service/src/__tests__/unit/README.md
- services/feature-toggle-service/src/__tests__/unit/action.provider.unit.ts
- services/feature-toggle-service/src/__tests__/unit/system.provider.unit.ts
- services/feature-toggle-service/src/__tests__/unit/tenant.provider.unit.ts
- services/feature-toggle-service/src/__tests__/unit/user.provider.unit.ts
gh-432
Added test cases for feature toggle service
Fixes #432
> test(feature-toggle-service): test case for feature toggle service 

- services/chat-service/migration.js
fix db-migrate import issue in chat service
> fix(chat-service): minor fix in migration.js

- services/notification-service/README.md
Corrected PubNubProvider.Config key in description in README.md
Just corrected key in description in README.md
> Corrected key in description in README.md

- services/authentication-service/src/modules/auth/login.controller.ts
- services/authentication-service/src/types.ts
fix keycloak logout after token refresh
Fixes #596
> fix(authentication-service): fix keycloak logout after token refresh

- sandbox/user-onboarding-example/src/app/tour.service.ts
gh-0
Used destructing to fix code smell
> fix(sandbox): fix code smell for user-onboarding example

- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/tour-step.ts
add support for angular component
Fixes #581
> fix(user-onboarding): add support for angular component

- sandbox/in-mail-example/package-lock.json
- sandbox/search-client-example/angular.json
- sandbox/search-client-example/tsconfig.json
- removed composite:true from tsconfig.json in search-client-example
- regenerated package lock for in-mail-example after deleting both package lock and node modules - this makes overrides work
> fix(sandbox): fix build failing in search-client-example and fix vulnerability issues in in-mail-example

- .github/workflows/main.yml
Add custom runner for workflows
> chore(chore): add custom runner

- services/chat-service/package-lock.json
- services/feature-toggle-service/package-lock.json
- services/in-mail-service/package-lock.json
- services/notification-service/package-lock.json
- services/payment-service/package-lock.json
- services/reporting-service/package-lock.json
- services/scheduler-service/package-lock.json
- services/search-service/package-lock.json
- services/video-conferencing-service/package-lock.json
- copied all changes of package lock from dependabot PRs and tested in local as npm audit check is not working for PRs.
> chore(deps): upgrade ejs to latest version v3.1.7

- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/src/enum.ts
- packages/cli/src/generators/datasource/templates/index.ts.tpl
- packages/cli/src/generators/datasource/templates/name.datasource.ts.tpl
- packages/cli/src/generators/datasource/templates/redis.datasource.ts.tpl
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/types/project.d.ts
When a microservice is created using authentication as base - cache datasource needs to be added.
Fixes #626
> fix(cli):set datasource name based on base service

- lerna.json
> chore(chore):ignore ocr from lerna

- lerna.json
- packages/cache/src/__tests__/acceptace/fixtures/product-error.repository.ts
- packages/cache/src/__tests__/acceptace/fixtures/product.repository.ts
- packages/cache/src/__tests__/unit/cache.mixin.unit.ts
- packages/ocr-parser/package.json
gh-00
added cache mixin to lerna json file.
Fixes #00
> chore(cache): added cache mixin to lerna

- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser.module.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/field-viewer/field-viewer.component.html
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/field-viewer/field-viewer.component.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/tabs/tabs.component.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/directives/text-select.directive.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/models/ocr.model.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/ocr-parser.component.scss
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/ocr-parser.component.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/pipes/dom-sanitizer.pipe.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/services/ocrData.service.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/public-api.ts
> fix(ocr-parser): fix sonar issues

- packages/cli/README.md
- packages/cli/src/generators/scaffold/index.ts
- packages/cli/src/generators/scaffold/templates/.cz-config.js.tpl
- packages/cli/src/generators/scaffold/templates/commitlint.config.js.tpl
- packages/cli/src/generators/scaffold/templates/package.json.tpl
gh-790
scaffold created through was missing the commit config added commitlint files.
Fixes #790 
> fix(cli): add commit config to cli

- services/authentication-service/src/controllers/forget-password.controller.ts
> fix(authentication-service): change response of forgot password for invalid user

- packages/core/src/components/swagger-authentication/keys.ts
> fix(core): fix swagger auth verifier key

- services/authentication-service/src/__tests__/acceptance/login.controller.acceptance.ts
- services/authentication-service/src/controllers/forget-password.controller.ts
Handle error throw from login helper service in forgot password controller.
Fixes #798
> fix(authentication-service): handle error thrown from login helper service

- packages/cli/README.md
- packages/cli/lib/base-generator.js
- packages/cli/src/commands/scaffold.ts
- packages/cli/src/generators/scaffold/index.ts
- packages/cli/src/generators/scaffold/templates/.cz-config.js.tpl
- packages/cli/src/generators/scaffold/templates/commitlint.config.js.tpl
- packages/cli/src/types.ts
Added a flag to set the issue prefix for commit linting.
Fixes #811
> fix(cli): add flag for issue prefix option

- sandbox/search-client-example/package.json
gh-00
fixing the version back to what it was
> chore(sandbox): version fix

- packages/core/package.json
- sandbox/feature-toggle-example/package.json
- sandbox/payment-example/backend/package.json
- services/feature-toggle-service/package-lock.json
- services/feature-toggle-service/src/__tests__/unit/strategy-helper.service.unit.ts
- services/feature-toggle-service/src/__tests__/unit/system-strategy.provider.unit.ts
- services/feature-toggle-service/src/__tests__/unit/tenant-strategy.provider.unit.ts
- services/feature-toggle-service/src/__tests__/unit/user-strategy.provider.unit.ts
- services/ocr-s3-service/src/controllers/ocr-object.controller.ts
- services/ocr-service/src/models/hocr-results.model.ts
- services/ocr-service/src/providers/fetch-client.service.ts
- services/ocr-service/src/repositories/hocr-results.repository.ts
- services/ocr-service/src/types.ts
- services/reporting-service/src/providers/metabase/metabase.provider.ts
- services/search-service/src/__tests__/unit/psql/query.builder.unit.ts
- services/search-service/src/classes/psql/query.builder.ts
- services/search-service/src/decorators/authentication-conditional.decorator.ts
- services/search-service/src/decorators/get-conditional.decorator.ts
- services/video-conferencing-service/src/providers/twilio/twilio.service.ts
gh-856
Sonar gate issues fix.
Fixes #856 
> perf(chore): sonar issues fix

- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/src/commands/update.ts
- packages/cli/src/generators/update/index.ts
- packages/cli/src/generators/update/types/types.ts
- packages/cli/src/types.ts
- packages/cli/src/types/update.d.ts
- packages/cli/src/update-generator.ts
> feat(cli): add new update command to cli

- packages/cache/src/mixins/cache.mixin.ts
- packages/feature-toggle/src/middlewares/feature-toggle-action.middleware.ts
- services/audit-service/src/types.ts
- services/authentication-service/src/types.ts
- services/chat-service/src/types.ts
- services/feature-toggle-service/src/__tests__/fixtures/bearer-token-verifier.provider.ts
- services/in-mail-service/src/types/service-config.type.ts
- services/ocr-service/src/providers/fetch-client.service.ts
- services/payment-service/src/types.ts
- services/reporting-service/src/types.ts
- services/user-tenant-service/src/types.ts
- services/video-conferencing-service/src/providers/twilio/twilio.service.ts
- services/video-conferencing-service/src/providers/twilio/types.ts
- services/video-conferencing-service/src/services/meeting-link-id-generator.provider.ts
> refactor(chore): fix sonar code smells

- sandbox/cache-example/package-lock.json
- sandbox/cache-example/package.json
gh-0
- add private true to package.json 
- update author to Sourcefuse and add license type MIT 
- regenerate package lock
> fix(sandbox): add private:true to cache example package.json

- packages/feature-toggle/src/index.ts
gh-437
adding export in feature toggle
> fix(feature-toggle): adding export in feature toggle

- packages/cli/README.md
- packages/cli/src/enum.ts
- packages/cli/src/generators/datasource/templates/index.ts.tpl
- packages/cli/src/generators/datasource/templates/redis.datasource.ts.tpl
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/microservice/templates/src/__tests__/acceptance/test-helper.ts.ejs
- packages/cli/src/types/project.d.ts
gh-789
Test cases were failing for generated microservices 
added datasources to test helper.
Fixes #789
> fix(cli): add datasource to test helper

- packages/cli/README.md
- packages/cli/src/generators/datasource/templates/name.datasource.ts.tpl
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/microservice/templates/.env.defaults
- packages/cli/src/generators/microservice/templates/.env.example
gh-914
- DB schema in datasource config for postgres
- remove database variables from .env in case of facade
- add the newly generated microservice to the scopes while commiting
Fixes #914
> fix(cli): cli changes for microservice and facade

- packages/cli/README.md
- packages/cli/src/commands/scaffold.ts
- packages/cli/src/generators/backstage-integration/index.ts
- packages/cli/src/generators/backstage-integration/templates/catalog-info.yml.tpl
- packages/cli/src/generators/backstage-integration/templates/mkdocs.yml.tpl
- packages/cli/src/generators/scaffold/index.ts
- packages/cli/src/types.ts
Add backstage integration flag for scaffold command.
> feat(cli): add backstage integration flag for scaffold

- sandbox/user-onboarding-example/package-lock.json
- sandbox/user-onboarding-example/package.json
gh-0
revert user-onboarding version in package json and lock.
> fix(sandbox): revert user-onboarding example version

- packages/cli/README.md
- packages/cli/lib/base-generator.js
- packages/cli/lib/utils.js
- packages/cli/package-lock.json
- packages/cli/src/generators/backstage-integration/templates/catalog-info.yml.tpl
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/microservice/templates/src/__tests__/acceptance/test-helper.ts.ejs
- packages/cli/src/generators/scaffold/templates/DEVELOPING.md.tpl
- packages/cli/src/generators/scaffold/templates/README.md.tpl
GH-0
Fixed writing cz-config file using fs.
GH-0
> fix(cli):fixed czconfig file using fs

- services/authentication-service/src/modules/auth/providers/azure-ad-verify.provider.ts
gh-00
Fix for azure ad - email present in upn of profile.
> fix(sandbox): email present in upn

- services/authentication-service/README.md
gh-0
readme changes for azure ad
> docs(authentication-service): readme changes for azure ad

- services/authentication-service/src/modules/auth/azure-login.controller.ts
gh-00
fix minor issues in azure oauth
> fix(authentication-service): fix minor issues in azure oauth

- lerna.json
- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/user-tenant-service/package.json
Made user-tenant-service private for auth service release.
> fix(user-tenant-service): made user-tenant-service private

- packages/core/package-lock.json
- packages/core/package.json
GH-1026
update loopback4-soft-delete version in core
GH-1026
> chore(deps): update loopback4-soft-delete version in core

- services/chat-service/src/__tests__/acceptance/attachement-file.controller.acceptance.ts
- services/chat-service/src/__tests__/mockdata/mockdata.ts
- services/chat-service/src/__tests__/mockdata/userCredsAndPermission.ts
- services/chat-service/src/component.ts
- services/chat-service/src/controllers/attachment-file.controller.ts
- services/chat-service/src/controllers/index.ts
- services/chat-service/src/enums/permission-key.enum.ts
- services/chat-service/src/models/attachment-file-dto.model.ts
- services/chat-service/src/models/attachment-file.model.ts
- services/chat-service/src/models/index.ts
- services/chat-service/src/repositories/attachment.repository.ts
- services/chat-service/src/repositories/index.ts
added attachment feature in chat service.
#576 
> feat(chat-service):add attachment feature in chat service.

- services/user-tenant-service/package.json
dummy commit for user-tenant
Fixes #1032
> feat(user-tenant-service): dummy commit for user-tenant

- lerna.json
- services/user-tenant-service/package.json
> feat(user-tenant-service): dummy user-tenant commit

- packages/core/src/repositories/default-transactional-user-modify-repository.base.ts
changed parent class of DefaultTransactionalUserModifyRepository to DefaultTransactionSoftCrudRepository.
Fixes #1031 
> fix(core): change parent class of DefaultTransactionalUserModifyRepository

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/utils.ts
Fixed IP address issue in RateLimitKeyGen.
Fixes #1039
> fix(core): IP address issue in RateLimitKeyGen

- packages/cli/README.md
- packages/cli/src/generators/microservice/index.ts
gh-1041
solved error while copying the migrations from base service
Fixes #1041
> fix(cli): fix the migration copy issue from base

- services/authentication-service/README.md
- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/authentication-service/package-lock.json
- services/authentication-service/package.json
- services/authentication-service/src/component.ts
- services/authentication-service/src/controllers/index.ts
- services/authentication-service/src/modules/auth/cognito-login.controller.ts
- services/authentication-service/src/modules/auth/index.ts
- services/authentication-service/src/modules/auth/providers/cognito-oauth2-verify.provider.ts
- services/authentication-service/src/providers/cognito-oauth2-signup.provider.ts
- services/authentication-service/src/providers/cognito-post-verify.provider.ts
- services/authentication-service/src/providers/cognito-pre-verify.provider.ts
- services/authentication-service/src/providers/index.ts
- services/authentication-service/src/providers/keys.ts
- services/authentication-service/src/providers/types.ts
APIs for Amazon Cognito OAuth Login.
Fixes #1045 
> feat(authentication-service): add APIs for Cognito OAuth

- packages/user-onboarding/.gitignore
- packages/user-onboarding/package.json
- packages/user-onboarding/projects/user-onboarding-lib/karma.conf.js
- packages/user-onboarding/projects/user-onboarding-lib/src/commands/StateCommands.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.spec.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.spec.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/mocks/tourService.mock.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/mocks/tourStore.mocks.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/models/video-model.ts
- packages/user-onboarding/projects/user-onboarding-lib/src/test.ts
- packages/user-onboarding/tsconfig.json
Unit test cases added for User Onboarding's services ie. TourStore service and TourService
Fixes GH-867
> test(user-onboarding): add unit test for TourStoreService and TourService

- packages/core/src/components/bearer-verifier/component.ts
- packages/core/src/components/bearer-verifier/providers/facades-bearer-asym-token-verify.provider.ts
add facade bearer asymmetric token verifier provider
GH-1212
add facade bearer asymmetric token verifier provider in bearer verifier component.
Fixes #1212 
> fix(core): add facade bearer asymmetric token verifier provider

- packages/custom-sf-changelog/writer-opts.js
- sandbox/auth-ms-basic-example/src/services/user-ops.service.ts
- sandbox/payment-example/frontend/src/OrdersPage.js
- services/user-tenant-service/src/services/user-operations.service.ts
Resolved some sonar code smells related to regex and react example in payment service
GH-1200
Fixes #1200
> refactor(chore): resolve sonar code smells

- services/authentication-service/README.md
update readme file for authentication service
GH-1327
update readme file for authentication service
Fixes #1327 
> docs(authentication-service): update readme for authentication service

- .czferc.js
- services/reporting-service/package.json
here after the reporting service will not be published
1345
Changing the reporting-service to private 
Fixes #1345 
> chore(reporting-service): making the reporting service private

- packages/search/projects/search-lib/package.json
gh-1353
making the package public to publish it -- search-client
Fixes #1353 
> fix(search-client): making the package public to publish it

- packages/search/projects/search-lib/bundle-element.ts
- packages/search/projects/search-lib/package.json
Need to pass both the directories to publish config to release it.
> fix(search-client): changes to release search element

- README.md
- Changes the getting started section in readme to illustrate step by step guide using sourceloop cli. (as mentioned [here](https://www.sourcefuse.com/blog/how-to-use-arc-by-sourcefuse-in-microservices-development/))
GH-1360
Fixes #1360 
> docs(chore): modify getting started section to use sl cli

- lerna.json
- packages/search/package.json
remove the search client from the build and release process
gh-00
remove the search client from the build and release process
> chore(search-client): remove the search client from the build and release process

- services/video-conferencing-service/src/services/chat-session.service.ts
> fix(video-service): fixed the date validation for meeting link generation

- services/chat-service/openapi.json
- services/chat-service/openapi.md
- services/chat-service/package.json
- services/feature-toggle-service/package.json
- services/payment-service/openapi.json
- services/payment-service/openapi.md
- services/payment-service/package.json
- services/user-tenant-service/openapi.json
- services/user-tenant-service/openapi.md
- services/user-tenant-service/package.json
Updates OpenAPI docs and fixes settings in some services for typedoc
> docs(chore): openapi docs maintenance

- .czferc.js
- .github/workflows/release.yml
- Adds `release.yml` file containing release steps excluding publish as of now to test out the version bumps correctness
> feat(workflows): add manual release action

- services/payment-service/openapi.json
- services/payment-service/openapi.md
- services/user-tenant-service/openapi.json
- services/user-tenant-service/openapi.md
updates outdated openapi docs
--
To check version bump in new manual release workflow
> chore(all-services): openapi docs maintenance

- .github/workflows/release.yml
- Re-enable tests before release and add lerna publish step
> fix(workflows): add publish step

- packages/search/projects/search-element/package.json
- packages/search/projects/search-lib/ng-package.json
- packages/search/projects/search-lib/package.json
gh-1386
changes to publish search client as web component
Fixes #1386 
> fix(search-client): changes to publish search client as web component

- packages/search/projects/search-element/package.json
- packages/search/projects/search-lib/bundle-element.ts
gh-1386
fix for releasing search client and element 
Fixes #1386
> fix(search-client): fix for releasing search-client

- packages/search/projects/search-element/package.json
- packages/search/projects/search-lib/package.json
gh-1386
correcting the package scope in the name field
Fixes #1386 
> fix(search-client): correcting the package scope in the name field

- .github/workflows/release.yml
- packages/search/projects/search-element/package.json
- packages/search/projects/search-lib/package.json
gh-00
changing the node version for release workflow
> chore(core): changing the node version in release workflow

- packages/search/projects/search-element/package.json
- packages/search/projects/search-lib/package.json
> fix(search-client): added missing test step

- services/user-tenant-service/README.md
- services/user-tenant-service/openapi.json
- services/user-tenant-service/openapi.md
- services/user-tenant-service/package-lock.json
- services/user-tenant-service/package.json
- services/user-tenant-service/src/component.ts
- services/user-tenant-service/src/models/audit.model.ts
- services/user-tenant-service/src/models/index.ts
- services/user-tenant-service/src/repositories/audit.repository.ts
- services/user-tenant-service/src/repositories/auth-client.repository.ts
- services/user-tenant-service/src/repositories/group-user-count-view.repository.ts
- services/user-tenant-service/src/repositories/group.repository.ts
- services/user-tenant-service/src/repositories/index.ts
- services/user-tenant-service/src/repositories/non-restricted-user-view.repository.ts
- services/user-tenant-service/src/repositories/role.repository.ts
- services/user-tenant-service/src/repositories/tenant-config.repository.ts
- services/user-tenant-service/src/repositories/tenant.repository.ts
- services/user-tenant-service/src/repositories/user-credentials.repository.ts
- services/user-tenant-service/src/repositories/user-group-view.repository.ts
- services/user-tenant-service/src/repositories/user-group.repository.ts
- services/user-tenant-service/src/repositories/user-level-permission.repository.ts
- services/user-tenant-service/src/repositories/user-tenant-prefs.repository.ts
- services/user-tenant-service/src/repositories/user-tenant.repository.ts
- services/user-tenant-service/src/repositories/user-view.repository.ts
- services/user-tenant-service/src/repositories/user.repository.ts
…n service
add support for configurable audit logs based on an env flag now users will be able to enable audit logs in the user tenant service
GH-1368
Fixes #1368 
> feat(user-tenant-service): add configurable audit log

- services/payment-service/src/index.ts
- services/video-conferencing-service/src/index.ts
> fix(payment-service): added exports

- services/chat-service/src/__tests__/acceptance/helper.ts
- services/chat-service/src/__tests__/unit/message-repository.unit.ts
add test case of has many relation for attachment file
GH-1395
add test case of has many relation for attachment file
Fixes #1395 
> test(chat-service): add test case for attachment file

- lerna.json
- sandbox/oidc-basic-example/package.json
Make OIDC Example private to exclude it from releases.
Authored by: @antriksha102 
> fix(oidc-example): make the example private

- packages/cli/package.json
update template dependencies
GH-1433
update template dependencies
Fixes #1433 
> chore(cli): update template dependencies

- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/models/ocr.model.ts
- services/authentication-service/src/providers/types.ts
Fixed some sonar code smells
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=sourcefuse_loopback4-microservice-catalog&open=AYifRb5egsd5pIGQfM2s&tab=why
> fix(chore): sonar code smells

- packages/cache/README.md
- packages/cache/src/__tests__/acceptance/cache.mixin.acceptance.ts
- packages/cache/src/mixins/cache.mixin.ts
Added ability to bypass cache using an env variable.
GH-1450
Fixes #1450
> feat(cache): add ability to skip cache

- .github/workflows/combine-prs.yml
To merge dependabot updates in single PR
Credits: https://github.com/hrvey/combine-prs-workflow
> feat(workflows): add combine pr workflow

- .github/workflows/combine-prs.yml
Added input to set PR titles in combine PR workflow
> feat(workflows): allow PR titles to be configured

- sandbox/auth-multitenant-example/package-lock.json
- sandbox/auth-multitenant-example/package.json
✅ This PR was created by the Combine PRs action by combining the following PRs:
#1492 [Snyk] Upgrade @loopback/repository from 5.1.0 to 5.1.5
#1491 [Snyk] Upgrade @loopback/service-proxy from 5.0.5 to 5.0.10
#1490 [Snyk] Upgrade dotenv from 16.0.3 to 16.1.3
#1489 [Snyk] Upgrade loopback4-authentication from 7.2.1 to 7.6.1
#1488 [Snyk] Upgrade loopback4-soft-delete from 7.0.2 to 7.3.2
> chore(deps): combine snyk updates

- services/audit-service/LICENSE
- services/audit-service/README.md
- Added MIT License
- Revamp documentation to mention the getting started steps one by one. 
- Mentioned the archival feature details.
- Added ARC Branding in header.
Fixes #1443 
> docs(audit-service): revamp documentation and use arc branding

- packages/cache/README.md
- Used the dark bg version for logo and changed the configuration binding syntax.
Related: #1442
> docs(cache): fix arc logo and configure step

- packages/cache/README.md
- Fixed the description for cacheProvider.
Related:#1442 
> docs(cache): fix description cacheProvider

- packages/core/src/secure-sequence.ts
Ratelimit action doesn't cover OBF path
GH-1546
add ratelimit action on OBF path
Fixes #1546 
> fix(core): add ratelimit action on OBF path

- services/audit-service/openapi.json
- services/audit-service/openapi.md
- services/audit-service/package-lock.json
- services/audit-service/package.json
Updated to 0.20.0
xlsx module updated
> fix(audit-service): xlsx module updated

- package-lock.json
- packages/user-onboarding/package-lock.json
- sandbox/audit-ms-example/package-lock.json
- sandbox/auth-ms-basic-example/package-lock.json
- sandbox/auth-multitenant-example/package-lock.json
- sandbox/cache-example/package-lock.json
- sandbox/feature-toggle-example/package-lock.json
- sandbox/in-mail-example/package-lock.json
- sandbox/nestjs-auth-ms-example/package-lock.json
- sandbox/oidc-basic-example/package-lock.json
- sandbox/pubnub-example/package-lock.json
- sandbox/scheduler-example/package-lock.json
- sandbox/search-client-example/package-lock.json
- sandbox/search-ms-example/package-lock.json
- sandbox/user-onboarding-example/package-lock.json
- sandbox/user-tenant-example/package-lock.json
- sandbox/video-conferencing-ms-example/package-lock.json
- sandbox/workflow-ms-example/package-lock.json
This PR addresses multiple vulnerabilities fixes in sandbox examples alerted in [Security](https://github.com/sourcefuse/loopback4-microservice-catalog/security) tab.
These are the ones that didn't need much manual attention, and hence no major upgrades involved.
> fix(deps): multiple vulnerabilities fix in sandbox examples

- sandbox/audit-ms-example/src/models/to-do.model.ts
- sandbox/auth-ms-basic-example/package-lock.json
- sandbox/auth-ms-basic-example/src/models/to-do.model.ts
- sandbox/auth-ms-basic-example/src/models/user.dto.ts
- sandbox/auth-multitenant-example/src/models/auth-client.model.ts
- sandbox/auth-multitenant-example/src/models/role.model.ts
- sandbox/auth-multitenant-example/src/models/tenant.model.ts
- sandbox/auth-multitenant-example/src/models/to-do.model.ts
- sandbox/auth-multitenant-example/src/models/user-credentials.model.ts
- sandbox/auth-multitenant-example/src/models/user-dto.model.ts
- sandbox/auth-multitenant-example/src/models/user-level-permission.model.ts
- sandbox/auth-multitenant-example/src/models/user-level-resource.model.ts
- sandbox/auth-multitenant-example/src/models/user-tenant.model.ts
- sandbox/auth-multitenant-example/src/models/user.model.ts
- sandbox/cache-example/package-lock.json
- sandbox/cache-example/package.json
- sandbox/cache-example/src/models/product.model.ts
- sandbox/chat-notification-pubnub-example/facade/src/models/pubnub-message-recipient.model.ts
- sandbox/chat-notification-pubnub-example/facade/src/models/pubnub-message.model.ts
- sandbox/chat-notification-pubnub-example/facade/src/models/pubnubnotification.model.ts
- sandbox/chat-notification-socketio-example/facade/src/models/socket-message-recipient.model.ts
- sandbox/chat-notification-socketio-example/facade/src/models/socket-message.model.ts
- sandbox/chat-notification-socketio-example/facade/src/models/socketnotification.model.ts
- sandbox/search-ms-example/src/models/to-do.model.ts
- sandbox/search-ms-example/src/models/user.model.ts
- sandbox/user-tenant-example/src/models/user.model.ts
- services/user-tenant-service/src/models/user.model.ts
This PR Removes useless constructor in mainly sandbox examples to resolve the sonar code smells.
> refactor(sandbox): remove useless constructors

- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/ocr-parser.component.ts
- sandbox/payment-example/frontend/src/CheckoutPage.js
- services/audit-service/src/__tests__/fixtures/providers/column-builder.service.ts
- services/audit-service/src/services/column-builder.service.ts
- services/audit-service/src/services/export-handler.service.ts
- services/authentication-service/src/modules/auth/otp.controller.ts
- services/authentication-service/src/providers/mfa.provider.ts
- services/notification-service/src/providers/notification-filter.service.ts
- services/search-service/src/classes/psql/query.builder.ts
- services/user-tenant-service/src/__tests__/bearer-token-verifier.provider.ts
Resolves sonar smells of remaining useless constructor ones and few others.
> refactor(chore): resolve sonar smells

- README.md
- packages/cli/tutorial.md
- Rewrite sourceloop headers
- Add ARC Logo and ARC API videos link
- Move the CLI tutorial to another markdown file and link it to make the main readme light and easy to follow.
> docs(chore): rewrite sourceloop headers and main readme

- lerna.json
- sandbox/telemed-app/backend/authentication-service/cdk/package.json
- sandbox/telemed-app/backend/notification-service/cdk/package.json
- sandbox/telemed-app/backend/video-conferencing-service/cdk/package.json
This PR is a temporary fix for the failing tests in cdk folders of Telemed app example.
By ignoring them in lerna run command.
> fix(sandbox): exclude cdk repos in lerna run command

- package-lock.json
- services/audit-service/README.md
- services/audit-service/openapi.json
- services/audit-service/openapi.md
- services/audit-service/package-lock.json
- services/audit-service/package.json
- services/audit-service/src/__tests__/helpers/db.helper.ts
- services/audit-service/src/__tests__/sample-data/mapping-log.ts
- services/audit-service/src/controllers/audit.controller.ts
- services/audit-service/src/keys.ts
- services/audit-service/src/models/custom-filter.model.ts
- services/audit-service/src/services/export-to-csv.service.ts
- services/audit-service/src/types.ts
Allows extra S3 config to be set
Fixes #1581 
> Added binding for s3

- services/authentication-service/src/modules/auth/login.controller.ts
fix sonar code smell
GH-1597
Fixed sonar code smell in authentication-service.
Fixes #1597 
> refactor(authentication-service): fix sonar code smell

- sandbox/telemed-app/backend/authentication-service/Dockerfile
- sandbox/telemed-app/backend/authentication-service/cdk/__tests__/__snapshots__/lambda.stack.test.ts.snap
- sandbox/telemed-app/backend/authentication-service/cdk/__tests__/lambda.stack.test.ts
- sandbox/telemed-app/backend/authentication-service/cdk/main.ts
- sandbox/telemed-app/backend/notification-service/Dockerfile
- sandbox/telemed-app/backend/notification-service/cdk/main.ts
- sandbox/telemed-app/backend/video-conferencing-service/Dockerfile
- sandbox/telemed-app/backend/video-conferencing-service/cdk/main.ts
update node version in runtime
update node latest version
> fix(sandbox): update node version in telemed app's runtime

- services/authentication-service/src/modules/auth/saml-login.controller.ts
change saml redirect api endpoint to use post  method
GH-1607
change saml redirect api endpoint to use post  method
Fixes #1607 
> fix(authentication-service): change saml redirect api endpoint 

- .github/workflows/release.yml
> fix(workflows): replace hard-coded usernames in release action

- services/authentication-service/README.md
- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/authentication-service/package-lock.json
- services/authentication-service/package.json
update loopback4-authentication version to latest
GH-1668
update loopback4-authentication version to latest
Added description about authenticating password using RSA encryption.
Fixes #1668 
> fix(deps): update loopback4-authentication version to latest

- .github/workflows/main.yml
This PR replaces the `m19c/action-lerna` action with explicit statements of lerna commands.
As it is using outdated version of lerna and no longer maintained.
> fix(workflows): replace lerna action with explicit commands

- packages/cli/package.json
- packages/cli/src/generators/project/templates/package.json.ejs
- packages/cli/src/generators/project/templates/package.plain.json.ejs
upgrade node version to 18 for sourceloop cli
Fixes #1706 
> chore(cli): upgrade node version to 18 for sourceloop cli

- packages/feature-toggle/CHANGELOG.md
- packages/feature-toggle/README.md
- packages/feature-toggle/src/__tests__/unit/feature-flag-action.provider.unit.ts
- packages/feature-toggle/src/classes/andFilterStrategy.ts
- packages/feature-toggle/src/classes/filterContext.ts
- packages/feature-toggle/src/classes/index.ts
- packages/feature-toggle/src/classes/orFilterStrategy.ts
- packages/feature-toggle/src/providers/feature-flag-action.provider.ts
- packages/feature-toggle/src/types.ts
- sandbox/feature-toggle-example/src/controllers/feature-toggle.controller.ts
Ability to pass multiple features in feature_flag decorator along with filter strategy i.e. AND, OR
GH-1711
> feat(feature-toggle): Ability to pass multiple features in feature_flag decorator along with filter strategy i.e. AND, OR

- .czferc.js
- services/survey-service/openapi.json
- services/survey-service/openapi.md
- services/survey-service/src/__tests__/acceptance/survey.controller.acceptance.ts
- services/survey-service/src/controllers/survey-question.controller.ts
- services/survey-service/src/services/survey-cycle.service.ts
- services/survey-service/src/services/survey-response.service.ts
- services/survey-service/src/services/survey.service.ts
gh-1700
Some minor fixes in survey service.
Fixes #1700 
> fix(survey-service): minor fix in survey service

- packages/cli/README.md
- packages/cli/src/enum.ts
- services/survey-service/package.json
Add survey-service as microservice in sourceloop cli
Fixes #1782 
> feat(cli): add survey-service in cli

- package-lock.json
- services/audit-service/src/controllers/audit.controller.ts
- services/audit-service/src/models/audit-log.model.ts
- services/survey-service/package.json
Enable audit service to archive zero entries without error
Fixes #1762 
> fix(audit-service): enable audit service to archive zero entries without error 

- .github/workflows/release.yml
gh-1798
make release workflow workspaces complaint
remove lerna bootstrap from workflow
Fixes #1798
> chore(workflows): make release workflow workspaces complaint

- packages/cli/package.json
Upgrade survey-service version in cli
Fixes #1797 
> feat(cli): upgrade survey-service version in cli

- packages/cli/src/generators/scaffold/templates/.husky/commit-msg
- packages/cli/src/generators/scaffold/templates/.husky/pre-commit
- packages/cli/src/generators/scaffold/templates/.husky/prepare-commit-msg
Integrate git secrets in cli so as to prevent committing secret keys and credentials into git repositories
Fixes #1794 
> feat(cli): integrate git secrets in cli

- packages/cli/package.json
- packages/cli/src/generators/extension/index.ts
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/microservice/templates/Dockerfile
- packages/cli/src/generators/microservice/templates/src/controllers/ping.controller.ts.ejs
- packages/cli/src/generators/scaffold/templates/lerna.json.tpl
- packages/cli/src/generators/scaffold/templates/package.json.tpl
- packages/cli/src/generators/update/index.ts
Make sourceloop CLI compatible with NPM workspaces
microservice command will generate according to workspace
Fixes #1695 
> feat(cli):make sourceloop cli compatible with npm workspaces

- packages/cli/package.json
make workspaces compliant
gh-00
Dummy commit to bump cli version
> fix(cli): extra commit to bump version

- lerna.json
gh-00
Reconfigure the packages property of lerna.json to detect core and cli 
> fix(chore): update lerna packages property

- DEVELOPING.md
- package.json
gh-1807
update the development guide according to npm workspaces
Fixes #1807 
> docs(chore): update the development guide according to npm workspaces

- README.md
gh-00
- add deprecation notice of v4 of cli
- updated the readme
> docs(cli): add deprecation notice of v4 of cli

- packages/cli/src/base-generator.ts
- packages/cli/src/generators/backstage-integration/index.ts
- packages/cli/src/generators/extension/index.ts
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/scaffold/index.ts
- packages/cli/src/generators/update/index.ts
- packages/cli/src/types/app.d.ts
- packages/cli/src/types/extension.d.ts
make the change that allow sourceloop/cli to run asynchronously. and be more efficient
Fixes #1792 
> refactor(cli): make flow async

- package-lock.json
- packages/core/src/types.ts
- services/chat-service/README.md
- services/chat-service/package.json
- services/chat-service/src/__tests__/unit/sequelize/sequelize.application.ts
- services/chat-service/src/__tests__/unit/sequelize/sequelize.component.ts
- services/chat-service/src/__tests__/utils/get-base-class.ts
- services/chat-service/src/component.ts
- services/chat-service/src/models/attachment-file.model.ts
- services/chat-service/src/repositories/sequelize/attachment-file.repository.ts
- services/chat-service/src/repositories/sequelize/index.ts
- services/chat-service/src/repositories/sequelize/message-recipient.repository.ts
- services/chat-service/src/repositories/sequelize/message.repository.ts
add sequelize support in chat service
GH-1350
add sequelize support in chat service
Fixes #1350 
> feat(chat-service): add sequelize support in chat service

- package-lock.json
- services/notification-service/README.md
- services/notification-service/package.json
- services/notification-service/src/__tests__/unit/sequelize/sequelize.application.ts
- services/notification-service/src/__tests__/unit/sequelize/sequelize.component.ts
- services/notification-service/src/__tests__/utils/get-base-class.ts
- services/notification-service/src/component.ts
- services/notification-service/src/controllers/notification-notification-user.controller.ts
- services/notification-service/src/controllers/notification-user-notification.controller.ts
- services/notification-service/src/controllers/notification-user.controller.ts
- services/notification-service/src/controllers/notification.controller.ts
- services/notification-service/src/repositories/sequelize/index.ts
- services/notification-service/src/repositories/sequelize/notification-user.repository.ts
- services/notification-service/src/repositories/sequelize/notification.repository.ts
add sequelize support in notification service
GH-1350
Add sequelize support in notification service
Fixes #1350 
> feat(notification-service): add sequelize support in notification service

- package-lock.json
- services/audit-service/README.md
- services/audit-service/package.json
- services/audit-service/src/__tests__/unit/sequelize.application.ts
- services/audit-service/src/__tests__/unit/sequelize.component.unit.ts
- services/audit-service/src/__tests__/utils/getBaseClass.ts
- services/audit-service/src/component.ts
- services/audit-service/src/controllers/audit.controller.ts
- services/audit-service/src/repositories/sequelize/audit-log.repository.ts
- services/audit-service/src/repositories/sequelize/index.ts
- services/audit-service/src/repositories/sequelize/job.repository.ts
- services/audit-service/src/repositories/sequelize/mapping-log.repository.ts
- services/audit-service/src/services/export-to-csv.service.ts
- services/audit-service/src/services/job-processing.service.ts
add sequelize support in audit service
GH-1350
add sequelize support in audit service
**Referencing  PR**
https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1422
Fixes #1350 
> feat(audit-service): add sequelize support in audit service

- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/migration-package/templates/packages/migrations/package.json.ejs
> fix(cli): update the migration scripts as per workspaces

- package-lock.json
- sandbox/auth-multitenant-example/Dockerfile
- sandbox/notification-socket-example/Dockerfile
- services/reporting-service/package.json
- services/video-conferencing-service/package.json
gh-00
fix the high issues of synk
Fixes #00
> chore(deps): fix the synk high issues

- services/video-conferencing-service/package.json
> chore(deps): fix synk issues

- package-lock.json
- package.json
- sandbox/auth-multitenant-example/package.json
- sandbox/notification-socket-example/package.json
- services/audit-service/package.json
gh-1851
fix the synk issues.
Fixes #1851 
> chore(deps): fix the synk issues

- packages/core/src/components/tenant-utilities/decorators/tenant-guard.decorator.ts
- packages/core/src/components/tenant-utilities/mixins/tenant-guard.mixin.ts
- packages/core/src/components/tenant-utilities/types.ts
add sequelize  support for tenant guard in sourceloop core
GH-1838
add sequelize  support for tenant guard in sourceloop core
Fixes #1838 
> feat(core): add sequelize tenant guard in sourceloop core

- package-lock.json
- services/audit-service/package.json
- services/authentication-service/package.json
- services/chat-service/package.json
- services/notification-service/package.json
- services/survey-service/package.json
- services/video-conferencing-service/package.json
change sequelize dependency to optional
GH-1866
change sequelize dependency to optional
Fixes #1866 
> fix(all-services): change sequelize dependency to optional

- services/user-tenant-service/README.md
- services/user-tenant-service/package.json
- services/user-tenant-service/src/__tests__/unit/sequelize/sequelize.application.ts
- services/user-tenant-service/src/__tests__/unit/sequelize/sequelize.component.ts
- services/user-tenant-service/src/__tests__/unit/utils/get-base-class.ts
- services/user-tenant-service/src/component.ts
- services/user-tenant-service/src/repositories/sequelize/auth-client.repository.ts
- services/user-tenant-service/src/repositories/sequelize/group.repository.ts
- services/user-tenant-service/src/repositories/sequelize/index.ts
- services/user-tenant-service/src/repositories/sequelize/role.repository.ts
- services/user-tenant-service/src/repositories/sequelize/tenant-config.repository.ts
- services/user-tenant-service/src/repositories/sequelize/tenant.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-credentials.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-group.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-invitation.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-level-permission.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-tenant-prefs.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-tenant.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-view.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user.repository.ts
add sequelize support in user tenant service
GH-1350
add sequelize support in user tenant service
Fixes #1350 
> feat(user-tenant-service): add sequelize support in user tenant service

- services/bpmn-service/README.md
- services/bpmn-service/package.json
- services/bpmn-service/src/application.ts
- services/bpmn-service/src/component.ts
- services/bpmn-service/src/repositories/sequelize/index.ts
- services/bpmn-service/src/repositories/sequelize/workflow-version.repository.ts
- services/bpmn-service/src/repositories/sequelize/workflow.repository.ts
add sequelize support in workflow service
GH-1350
add sequelize support in BPMN service
Fixes #1350 
> feat(bpmn-service): add sequelize support in workflow service

- services/payment-service/README.md
- services/payment-service/package.json
- services/payment-service/src/__tests__/unit/sequelize/sequelize.application.ts
- services/payment-service/src/__tests__/unit/sequelize/sequelize.component.ts
- services/payment-service/src/__tests__/unit/utils/get-base-class.ts
- services/payment-service/src/component.ts
- services/payment-service/src/controllers/orders.controller.ts
- services/payment-service/src/controllers/payment-gateways.controller.ts
- services/payment-service/src/controllers/subscriptions-transactions.controller.ts
- services/payment-service/src/controllers/subscriptions.controller.ts
- services/payment-service/src/controllers/templates.controller.ts
- services/payment-service/src/controllers/transactions-subscriptions.controller.ts
- services/payment-service/src/keys.ts
- services/payment-service/src/repositories/sequelize/index.ts
- services/payment-service/src/repositories/sequelize/orders.repository.ts
- services/payment-service/src/repositories/sequelize/payment-gateways.repository.ts
- services/payment-service/src/repositories/sequelize/subscriptions.repository.ts
- services/payment-service/src/repositories/sequelize/templates.repository.ts
- services/payment-service/src/repositories/sequelize/transactions.repository.ts
- services/payment-service/src/types.ts
add sequelize support in payment service
GH-1350
add sequelize support in payment service
Fixes #1350
> feat(payment-service): add sequelize support in payment service

- package-lock.json
- services/audit-service/package.json
- services/authentication-service/package.json
- services/bpmn-service/package.json
- services/chat-service/package.json
- services/notification-service/package.json
- services/payment-service/package.json
- services/survey-service/package.json
- services/user-tenant-service/package.json
- services/video-conferencing-service/package.json
add sequelize as optional dependency
GH-1866
add sequelize as optional dependency
Fixes #1866 
> fix(all-services): add sequelize as optional dependency

- package-lock.json
- services/scheduler-service/README.md
- services/scheduler-service/package.json
- services/scheduler-service/src/__tests__/unit/sequelize/sequelize.application.ts
- services/scheduler-service/src/__tests__/unit/sequelize/sequelize.component.ts
- services/scheduler-service/src/__tests__/unit/utils/get-base-class.ts
- services/scheduler-service/src/component.ts
- services/scheduler-service/src/keys.ts
- services/scheduler-service/src/repositories/sequelize/attachment.repository.ts
- services/scheduler-service/src/repositories/sequelize/attendee.repository.ts
- services/scheduler-service/src/repositories/sequelize/audit.repository.ts
- services/scheduler-service/src/repositories/sequelize/calendar.repository.ts
- services/scheduler-service/src/repositories/sequelize/event-attendee-view.repository.ts
- services/scheduler-service/src/repositories/sequelize/event.repository.ts
- services/scheduler-service/src/repositories/sequelize/index.ts
- services/scheduler-service/src/repositories/sequelize/settings.repository.ts
- services/scheduler-service/src/repositories/sequelize/subscription.repository.ts
- services/scheduler-service/src/repositories/sequelize/theme.repository.ts
- services/scheduler-service/src/repositories/sequelize/working-hour.repository.ts
add sequelize support in scheduler service
GH-1350
add sequelize support in scheduler service
Fixes #1350 
> feat(scheduler-service): add sequelize support in scheduler service

- packages/cli/README.md
- services/notification-service/README.md
- services/notification-service/src/controllers/notification.controller.ts
Fixed Issue in draft notification API as it has a bug and it was not drafting notification
Modified read me file and mentioned about new grouping feature
GH-1806
> chore(chore): modified readme file and fix for draft API issue

- packages/core/src/repositories/default-transactional-user-modify-repository.base.ts
- packages/core/src/repositories/default-user-modify-crud.repository.base.ts
- services/notification-service/src/controllers/notification-user.controller.ts
- services/notification-service/src/controllers/notification.controller.ts
gh-1124
Revert the changes done in - https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1881
Fixes #1124
> revert(all-services): revert the extra checks added for createall method

- services/video-conferencing-service/migrations/mysql/migrations/20240104074814-alter-table-for-soft-delete.js
- services/video-conferencing-service/migrations/mysql/migrations/sqls/20240104074814-alter-table-for-soft-delete-down.sql
- services/video-conferencing-service/migrations/mysql/migrations/sqls/20240104074814-alter-table-for-soft-delete-up.sql
- services/video-conferencing-service/migrations/pg/migrations/20240104074629-alter-table-for-soft-delete.js
- services/video-conferencing-service/migrations/pg/migrations/sqls/20240104074629-alter-table-for-soft-delete-down.sql
- services/video-conferencing-service/migrations/pg/migrations/sqls/20240104074629-alter-table-for-soft-delete-up.sql
added missing migrations for soft delete in video_session_details table
GH-1821
> feat(video-conferencing-service): added missing migrations

- services/search-service/src/classes/base/query.builder.ts
allow model name to be different from the one present in db
Fixes #1820 
> fix(search-service): allow model name to be different from the one present in db

- services/notification-service/migrations/pg/migrations/sqls/20210501132806-init-up.sql
gh-00
rectify migration syntax error
> fix(notification-service): rectify migration syntax error

- .czferc.js
- .github/workflows/audit.yml
- .github/workflows/main.yml
- README.md
new workflow for audit
gh-1861
Changed the name of existing workflow, removed extra console
Added a new audit workflow
Added the synk badge
Fixes #1861 
> chore(workflows): update the test workflow and add synk badge in readme

- packages/core/README.md
hide api on swagger and swagger stats
gh-1910
Add the documentation about how to hide API on swagger and swagger stats
Fixes #1910 
You can refer here - https://github.com/yeshamavani/GH-1910
> docs(core): update the docs to write about hiding apis

- packages/cli/src/generators/microservice/index.ts
- packages/cli/src/generators/scaffold/templates/package.json.tpl
github action failing in microservice scaffold - backstage
Fixes #1905 
> fix(cli): github action failing in microservice scaffold - backstage

- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/enum.ts
add task service in @sourceloop/cli template dependencies
GH-1932
Fixes #1932
> feat(cli): add task service

- packages/cli/package.json
update sourceloop survey service version in cli's
template dependencies
gh-00
> chore(deps): update survey sevice in cli template

- packages/cli/README.md
- packages/cli/src/generators/microservice/index.ts
- packages/core/src/__tests__/integration/tenant-utilities/repo-with-guarded-tenant.decorator.decorator.ts
- services/audit-service/src/__tests__/helpers/db.helper.ts
- services/audit-service/src/__tests__/integration/archive-log.controller.unit.ts
- services/audit-service/src/__tests__/integration/export-log.controller.unit.ts
- services/audit-service/src/__tests__/integration/job-processing.service.unit.ts
- services/payment-service/openapi.json
- services/payment-service/openapi.md
- services/reporting-service/openapi.json
- services/reporting-service/openapi.md
- services/user-tenant-service/openapi.json
- services/user-tenant-service/openapi.md
> chore(all-services): sonar fix

- .husky/pre-commit
- services/authentication-service/src/providers/keycloak-authentication.provider.ts
> fix(authentication-service): remove extra env for keycloack

- packages/cache/src/mixins/cache.mixin.ts
- packages/cli/README.md
- packages/cli/src/__tests__/commands/extension.test.ts
- packages/cli/src/__tests__/commands/microservice.test.ts
- packages/cli/src/__tests__/commands/scaffold.test.ts
- packages/cli/src/__tests__/commands/update.test.ts
- packages/cli/src/generators/cdk/index.ts
- packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/field-viewer/field-viewer.component.html
- sandbox/cache-example/public/index.html
- sandbox/oauth-example/src/repositories/user.repository.ts
- sandbox/oidc-basic-example/src/providers/custom-find-account.provider.ts
- services/authentication-service/src/__tests__/fixtures/datasources/auth-cache-mock.datasource.ts
- services/authentication-service/src/__tests__/fixtures/datasources/auth-mock-data.datasource.ts
- services/bpmn-service/src/__tests__/datasources/workflowdb.datasource.ts
- services/chat-service/src/datasources/pgdb.datasource.ts
- services/feature-toggle-service/src/__tests__/fixtures/datasources/feature-toggle-mock.datasource.ts
- services/notification-service/src/__tests__/datasources/notification-cache.datasource.ts
- services/notification-service/src/__tests__/datasources/notification-db.datasource.ts
- services/oidc-service/public/index.html
- services/oidc-service/src/repositories/user.repository.ts
- services/scheduler-service/src/__tests__/datasources/scheduler-db.datasource.ts
- services/survey-service/src/__tests__/datasources/survey-mock.datasource.ts
- services/user-tenant-service/src/__tests__/datasources/auth.datasource.ts
- services/user-tenant-service/src/__tests__/datasources/cache.datasource.ts
Fix the pending sonar issues in all services
Fixes #2013 
> fix(all-services): fix the pending sonar issues in all services

- services/user-tenant-service/src/repositories/auth-client.repository.ts
- services/user-tenant-service/src/repositories/group.repository.ts
- services/user-tenant-service/src/repositories/role.repository.ts
- services/user-tenant-service/src/repositories/sequelize/auth-client.repository.ts
- services/user-tenant-service/src/repositories/sequelize/group.repository.ts
- services/user-tenant-service/src/repositories/sequelize/role.repository.ts
- services/user-tenant-service/src/repositories/sequelize/tenant-config.repository.ts
- services/user-tenant-service/src/repositories/sequelize/tenant.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-credentials.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-group.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-invitation.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-level-permission.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-tenant-prefs.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-tenant.repository.ts
- services/user-tenant-service/src/repositories/sequelize/user-view.repository.ts
- services/user-tenant-service/src/repositories/tenant-config.repository.ts
- services/user-tenant-service/src/repositories/tenant.repository.ts
- services/user-tenant-service/src/repositories/user-credentials.repository.ts
- services/user-tenant-service/src/repositories/user-group.repository.ts
- services/user-tenant-service/src/repositories/user-invitation.repository.ts
- services/user-tenant-service/src/repositories/user-level-permission.repository.ts
- services/user-tenant-service/src/repositories/user-tenant-prefs.repository.ts
- services/user-tenant-service/src/repositories/user-tenant.repository.ts
- services/user-tenant-service/src/repositories/user-view.repository.ts
enable the ability to override the model
Fixes #2006 
> fix(user-tenant-service): enable the ability to override the model

- services/user-tenant-service/src/__tests__/acceptance/tenant-role.controller.acceptance.ts
- services/user-tenant-service/src/__tests__/acceptance/tenant-user.controller.acceptance.ts
- services/user-tenant-service/src/component.ts
- services/user-tenant-service/src/controllers/tenant-role.controller.ts
- services/user-tenant-service/src/controllers/tenant-user.controller.ts
- services/user-tenant-service/src/keys.ts
- services/user-tenant-service/src/services/index.ts
- services/user-tenant-service/src/services/tenant-operations.service.ts
- services/user-tenant-service/src/services/user-operations.service.ts
secure PATCH and PUT users API
Fixes #2004 
> fix(user-tenant-service): secure PATCH and PUT users API

- package-lock.json
- packages/core/README.md
- packages/core/package.json
- packages/core/src/component.ts
- packages/core/src/keys.ts
- packages/core/src/middlewares/add-tenantid-action.middleware.ts
- packages/core/src/middlewares/index.ts
- packages/core/src/middlewares/tenant-context.middleware.ts
- packages/core/src/providers/index.ts
- packages/core/src/providers/tenantid-encryption.provider.ts
- packages/core/src/types.ts
add provision in logs to save tenant information
GH-1918
Added addTenantIdmiddleware for adding tenant Id to the request context that will add tenant context in OBF logs automatically
Fixes #1918 
> feat(core): add provision in logs to save tenant information

- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/authentication-service/src/component.ts
- services/authentication-service/src/enums/sign-up-provider.enum.ts
- services/authentication-service/src/modules/auth/controllers/logout.controller.ts
- services/authentication-service/src/providers/cognito-authentication.provider.ts
- services/authentication-service/src/providers/google-authentication.provider.ts
- services/authentication-service/src/providers/index.ts
- services/authentication-service/src/providers/keys.ts
- services/authentication-service/src/providers/user-validation.provider.ts
Provide support to manage tokens for user logging in and logging out via cognito
Fixes #1939 
> fix(authentication-service):provide support to manage tokens for user logging in and logging out via cognito

- package-lock.json
- services/authentication-service/README.md
- services/authentication-service/package.json
- services/authentication-service/src/component.ts
- services/authentication-service/src/keys.ts
- services/authentication-service/src/providers/password-hashing.provider.ts
- services/authentication-service/src/providers/password-verify.provider.ts
- services/authentication-service/src/providers/types.ts
- services/authentication-service/src/repositories/user.repository.ts
implement configurable hashing
GH-2038
Configurable Hashing algorithm option
Fixes #2038 
> feat(authentication-service): implement configurable hashing

- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/authentication-service/src/__tests__/acceptance/login-activity.controller.acceptance.ts
- services/authentication-service/src/__tests__/fixtures/datasources/userCredsAndPermission.ts
- services/authentication-service/src/component.ts
- services/authentication-service/src/controllers/index.ts
- services/authentication-service/src/controllers/login-activity.controller.ts
- services/authentication-service/src/enums/login-type.enum.ts
- services/authentication-service/src/models/active-users-filter.model.ts
- services/authentication-service/src/models/index.ts
- services/authentication-service/src/services/active-user-fliter-builder.service.ts
- services/authentication-service/src/services/index.ts
gh-1517
filtering option in activity logs
this filter is via a service that if user wants can override.
Fixes #1517 
> feat(authentication-service): filtering option in activity logs

- services/bpmn-service/openapi.json
- services/bpmn-service/openapi.md
- services/bpmn-service/src/__tests__/acceptance/workflow.controller.acceptance.ts
- services/bpmn-service/src/controllers/workflow.controller.ts
- services/bpmn-service/src/enums/permission-key.enum.ts
Added a new permission to execute workflow , and added it to the concerned API.
Fixes GH-2053
> fix(bpmn-service): added and changed permission for execute workflow api

- packages/core/src/components/tenant-utilities/keys.ts
- packages/core/src/components/tenant-utilities/services/tenant-guard.service.ts
- packages/core/src/components/tenant-utilities/types.ts
add tenant utilities config , related to issue gh 1942
Fixes #1942 
> feat(core): add tenant utilities config related to issue gh 1942

- services/user-tenant-service/src/__tests__/acceptance/test-helper.ts
- services/user-tenant-service/src/__tests__/acceptance/user-webhook.controller.acceptance.ts
> feat(user-tenant-service): add user webhook test cases

- services/authentication-service/src/providers/bearer-verify.provider.ts
- services/authentication-service/src/providers/jwt-signer.provider.ts
- services/authentication-service/src/providers/jwt-verify.provider.ts
- services/payment-service/src/__tests__/fixtures/application.ts
- services/user-tenant-service/src/__tests__/acceptance/test-helper.ts
- services/user-tenant-service/src/__tests__/acceptance/user-webhook.controller.acceptance.ts
- services/user-tenant-service/src/component.ts
- services/user-tenant-service/src/controllers/user-webhook.controller.ts
- services/user-tenant-service/src/interceptors/user-webhook-verifier.interceptor.ts
- services/user-tenant-service/src/keys.ts
- services/user-tenant-service/src/models/dtos/address-dto.model.ts
- services/user-tenant-service/src/models/dtos/user-webhook-dto.model.ts
- services/user-tenant-service/src/repositories/tenant.repository.ts
- services/user-tenant-service/src/services/user-webhook-helper.service.ts
- services/user-tenant-service/src/types.ts
gh-2095
sonar fixes
Fixes #2095
> chore(all-services): sonar fixes

- services/authentication-service/README.md
- services/authentication-service/openapi.json
- services/authentication-service/openapi.md
- services/authentication-service/src/modules/auth/controllers/otp.controller.ts
- services/authentication-service/src/modules/auth/models/otp-login-request.dto.ts
fix verify otp flow for mfa
GH-2099
fix verify otp flow for mfa
Fixes #2099 
> fix(authentication-service): fix verify otp flow for mfa

- services/audit-service/openapi.json
- services/audit-service/openapi.md
- services/audit-service/src/__tests__/integration/archive-log.controller.unit.ts
- services/audit-service/src/__tests__/sample-data/archive-log.ts
- services/audit-service/src/models/custom-filter.model.ts
- services/audit-service/src/services/job-processing.service.ts
- services/audit-service/src/utils/construct-where.ts
- services/audit-service/src/utils/file-check.ts
add support for multiple actedon and actiongroup
GH-2119
add support for multiple actedon and actiongroup.
Fixes #2119 
> feat(audit-service): add support for multiple actedon and actiongroup

- services/task-service/src/commands/create-task.ts
> fix(deps): sonar fix

- sandbox/user-tenant-example/package.json
gh-00
Dummy commit to update the version.
> fix(sandbox): updated the user tenant example version

- services/feature-toggle-service/package.json
model changes
gh-2141
Dummy commit to bump version
Fixes #2141
> feat(feature-toggle): dummy commit to bump version

- services/audit-service/package.json
> feat(audit-service): dummy commit to bump version

- packages/cli/src/generators/microservice/templates/.eslintrc.js.ejs
add updated .eslintrc file for microservices
GH-2149
add updated .eslintrc file for microservices
Fixes #2149 
> fix(cli): add updated .eslintrc file for microservices

- packages/core/src/component.ts
- packages/core/src/types.ts
GH-2165
Updated condition to set i18n localization.
Fixes #2165 
> fix(core): updated condition to set i18n localization

- packages/core/src/casbin-secure-sequence.ts
- packages/core/src/secure-sequence.ts
- packages/core/src/service-sequence.ts
gh-2168
Updated condition to set locale for error messages.
Fixes #2168 
> fix(core): add condition to set locale for error message

- packages/core/src/repositories/default-transactional-user-modify-repository.base.ts
- packages/core/src/repositories/default-user-modify-crud.repository.base.ts
gh-2158
revert the changes of 2158
> fix(core): revert the changes of 2158

- services/audit-service/package.json
update types version to use exporter
GH-2088
Fixes #2088
> fix(audit-service): update types version to use exporter

- services/audit-service/migration.js
- services/authentication-service/migration.js
- services/bpmn-service/migration.js
- services/chat-service/migration.js
- services/feature-toggle-service/migration.js
- services/in-mail-service/migration.js
- services/notification-service/migration.js
- services/oidc-service/migration.js
- services/payment-service/migration.js
- services/reporting-service/migration.js
- services/scheduler-service/migration.js
- services/search-service/migration.js
- services/task-service/migration.js
- services/user-tenant-service/migration.js
- services/video-conferencing-service/migration.js
update migration.js to run migration on post install
Fixes #2003 
> fix(all-services): update migration.js to run migration on post install

- services/search-service/src/keys.ts
export datasource name as expected by cli in search service
GH-2136
export datasource name as expected by cli in search service
Fixes #2136 
> fix(search-service): export datasource name as expected by cli in search service

- services/audit-service/package.json
fix types version export
GH-2088
Fixes #2088 
> fix(audit-service): fix types version export

- packages/cli/src/generators/microservice/templates/src/__tests__/acceptance/test-helper.ts.ejs
add host in env of default test cases of scaffolded service
Fixes #2218 
> fix(cli): add host in env of default test cases of scaffolded service

- sandbox/telemed-app/backend/authentication-service/src/config.ts
- sandbox/telemed-app/backend/notification-service/src/config.ts
- sandbox/telemed-app/backend/video-conferencing-service/src/config.ts
> fix(sandbox): remove sonar issues

- sandbox/auth-ms-basic-example/src/datasources/auth-cache.datasource.ts
- sandbox/auth-ms-basic-example/src/services/user-ops.service.ts
update imports in user ops service
> fix(sandbox): update imports in user ops service

- sandbox/feature-toggle-example/README.md
- sandbox/feature-toggle-example/migrations/20230612141912-update-tables.js
- sandbox/feature-toggle-example/migrations/sqls/20210913104858-initial-up.sql
- sandbox/feature-toggle-example/migrations/sqls/20230612141912-update-tables-down.sql
- sandbox/feature-toggle-example/migrations/sqls/20230612141912-update-tables-up.sql
- sandbox/feature-toggle-example/package.json
- sandbox/feature-toggle-example/src/application.ts
refactor code
MIGRATION CHANGE:
migration-20230612141912- refactor code
migration-20210913104858- refactor code
0
> refactor(sandbox): refactor feature toggle example sandbox

- services/authentication-service/src/modules/auth/controllers/logout.controller.ts
update the logout keycloak url
> fix(authentication-service): update the logout keycloak url

- packages/cli/src/generators/scaffold/templates/.github/workflows/trivy.yaml
- packages/cli/src/generators/scaffold/templates/package.json.tpl
- packages/cli/src/generators/scaffold/templates/trivy.yml
Add trivy scan in scaffold CLI
GH-2296
> feat(ci-cd): add trivy scan in scaffold CLI

- package-lock.json
- package.json
1. update cz-format-extension deps
> fix(chore): update cz-format-extension deps

- package-lock.json
- package.json
- packages/cli/README.md
- packages/file-utils/package.json
links update in readme file
GH-2304
> fix(cli): links update in readme file

- packages/cli/src/enum.ts
add support for reporting-service
GH-2315
> feat(cli): add support for reporting-service
